export const featuredProducts = [
  {
    id: "1",
    name: "Personalized Wooden Name Plate",
    price: 1299,
    image: "/images/products/wooden-nameplate.jpg",
    category: "Home Decor",
    isCustomizable: true,
    isBestseller: true,
  },
  {
    id: "2",
    name: "Brass Photo Frame",
    price: 1899,
    image: "/images/products/brass-photo-frame.jpg",
    category: "Photo Frames",
    isCustomizable: true,
  },
  {
    id: "3",
    name: "Personalized Metal Keychain",
    price: 599,
    image: "/images/products/personalized-keychain.jpg",
    category: "Keychains",
    isNew: true,
    isCustomizable: true,
  },
  {
    id: "4",
    name: "Wedding Gift Box Set",
    price: 3999,
    image: "/images/products/wedding-gift-box.jpg",
    category: "Gift Sets",
    isBestseller: true,
  },
]

export const allProducts = [
  ...featuredProducts,
  {
    id: "5",
    name: "Wooden Wall Art",
    price: 2299,
    image: "/images/products/wooden-wall-art.jpg",
    category: "Wall Art",
    isCustomizable: true,
  },
  {
    id: "6",
    name: "Decorative Ceramic Vase",
    price: 1599,
    image: "/images/products/decorative-vase.jpg",
    category: "Home Decor",
    isNew: true,
  },
  {
    id: "7",
    name: "Leather Bound Journal",
    price: 899,
    image: "/images/products/leather-journal.jpg",
    category: "Stationery",
    isCustomizable: true,
  },
  {
    id: "8",
    name: "Handcrafted Ceramic Bowls",
    price: 1299,
    image: "/images/products/ceramic-bowls.jpg",
    category: "Home Decor",
    isBestseller: true,
  },
  {
    id: "9",
    name: "Custom Cutting Board",
    price: 1799,
    image: "/images/products/custom-cutting-board.jpg",
    category: "Kitchen",
    isCustomizable: true,
    isNew: true,
  },
  {
    id: "10",
    name: "Brass Candle Holders",
    price: 2499,
    image: "/images/products/brass-candle-holders.jpg",
    category: "Home Decor",
    isCustomizable: true,
  },
  {
    id: "11",
    name: "Wooden Jewelry Box",
    price: 2199,
    image: "/images/products/wooden-jewelry-box.jpg",
    category: "Storage",
    isCustomizable: true,
  },
  {
    id: "12",
    name: "Anniversary Gift Hamper",
    price: 3499,
    image: "/images/products/wedding-gift-box.jpg",
    category: "Gift Sets",
    isCustomizable: true,
  },
]

export const categories = [
  {
    id: "festive",
    name: "Festive Treasures",
    description: "Celebrate special occasions with our festive collection",
    image: "/images/collections/festive-collection.jpg",
  },
  {
    id: "wedding",
    name: "Wedding Elegance",
    description: "Timeless gifts and decor for the perfect wedding",
    image: "/images/collections/wedding-collection.jpg",
  },
  {
    id: "custom",
    name: "Bespoke Creations",
    description: "Personalized gifts crafted to your specifications",
    image: "/images/collections/custom-collection.jpg",
  },
  {
    id: "home-decor",
    name: "Home Decor",
    description: "Beautiful pieces to enhance your living space",
    image: "/images/products/wooden-nameplate.jpg",
  },
  {
    id: "photo-frames",
    name: "Photo Frames",
    description: "Preserve your precious memories in style",
    image: "/images/products/brass-photo-frame.jpg",
  },
  {
    id: "gift-sets",
    name: "Gift Sets",
    description: "Curated gift boxes for every occasion",
    image: "/images/products/wedding-gift-box.jpg",
  },
]
